# Bài tập về nhà: Singular Value Decomposition (SVD)

Bài làm gồm 2 câu:
1. Phân rã ma trận rank thấp bằng SVD.
2. Chọn số thành phần $k$ cho Truncated SVD dựa trên tỷ lệ năng lượng.


In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

# Câu 1. Phân rã ma trận

Cho ma trận:

$$
A=
\begin{bmatrix}
1 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
0 & 1 & 1
\end{bmatrix}
\in\mathbb{R}^{4\times3}
$$


In [2]:
A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)
A

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

## Bước 1. Các cột của $A$ phụ thuộc tuyến tính. Tìm rank(A)

Gọi các cột của $A$ là:

$$
c_1=\begin{bmatrix}1\\0\\1\\0\end{bmatrix},\quad
c_2=\begin{bmatrix}0\\1\\0\\1\end{bmatrix},\quad
c_3=\begin{bmatrix}1\\1\\1\\1\end{bmatrix}
$$

Vì:

$$
c_3 = c_1 + c_2
$$

Do đó $c_1,c_2,c_3$ **phụ thuộc tuyến tính**.

Mặt khác $c_1,c_2$ độc lập tuyến tính với nhau. Vậy không gian cột của $A$ có số chiều đúng bằng 2.

$$
\boxed{\operatorname{rank}(A)=2}
$$


In [3]:
print("rank(A) =", np.linalg.matrix_rank(A))
print("c1 + c2 - c3 =", A[:,0] + A[:,1] - A[:,2])  # kiểm tra c3 = c1 + c2

rank(A) = 2
c1 + c2 - c3 = [0. 0. 0. 0.]


## Bước 2. Tính $A^\top A$

$$
A^\top A =
\begin{bmatrix}
c_1\cdot c_1 & c_1\cdot c_2 & c_1\cdot c_3\\
c_2\cdot c_1 & c_2\cdot c_2 & c_2\cdot c_3\\
c_3\cdot c_1 & c_3\cdot c_2 & c_3\cdot c_3
\end{bmatrix}
=
\begin{bmatrix}
2 & 0 & 2\\
0 & 2 & 2\\
2 & 2 & 4
\end{bmatrix}
$$

(vì $c_1\cdot c_1=2,\ c_1\cdot c_2=0,\ c_1\cdot c_3=2,\ c_2\cdot c_2=2,\ c_2\cdot c_3=2,\ c_3\cdot c_3=4$).


In [4]:
M = A.T @ A
display(M)

array([[2., 0., 2.],
       [0., 2., 2.],
       [2., 2., 4.]])

## Bước 3–4. Eigenvalues và eigenvectors trực chuẩn của $A^\top A$, sắp xếp giảm dần

**Đa thức đặc trưng.** Với $M=A^\top A$:

$$
\det(M-\lambda I)=\det\!\begin{bmatrix}2-\lambda & 0 & 2\\ 0& 2-\lambda& 2\\ 2&2&4-\lambda\end{bmatrix}
$$

Khai triển theo hàng 1:

$$
= (2-\lambda)\big[(2-\lambda)(4-\lambda)-4\big] + 2\big[-2(2-\lambda)\big]
= (2-\lambda)\Big[(2-\lambda)(4-\lambda)-8\Big]
$$

Mà $(2-\lambda)(4-\lambda)=\lambda^2-6\lambda+8$, nên biểu thức trong ngoặc là $\lambda^2-6\lambda$. Vậy:

$$
\det(M-\lambda I) = (2-\lambda)\cdot\lambda\cdot(\lambda-6) = 0
$$

$$
\Rightarrow \lambda \in \{0,\,2,\,6\}
$$

Sắp xếp giảm dần: $\lambda_1=6,\ \lambda_2=2,\ \lambda_3=0$ (tổng $=8=\operatorname{trace}(M)$).

**Eigenvector ứng với $\lambda_1=6$:** giải $(M-6I)x=0$:

$$
\begin{bmatrix}-4&0&2\\0&-4&2\\2&2&-2\end{bmatrix}x=0
\ \Rightarrow\ z=2x,\ z=2y \Rightarrow x=y,\ z=2x
$$

Vector riêng $(1,1,2)$, chuẩn hoá: $\ v_1=\dfrac{1}{\sqrt6}(1,1,2)^\top$.

**Eigenvector ứng với $\lambda_2=2$:** giải $(M-2I)x=0$:

$$
\begin{bmatrix}0&0&2\\0&0&2\\2&2&2\end{bmatrix}x=0
\ \Rightarrow\ z=0,\ x+y=0
$$

Vector riêng $(1,-1,0)$, chuẩn hoá: $\ v_2=\dfrac{1}{\sqrt2}(1,-1,0)^\top$.

**Eigenvector ứng với $\lambda_3=0$:** giải $(M-0I)x=0 \Leftrightarrow Mx=0$:

$$
x+z=0,\quad y+z=0 \ \Rightarrow\ x=y=-z
$$

Vector riêng $(1,1,-1)$, chuẩn hoá: $\ v_3=\dfrac{1}{\sqrt3}(1,1,-1)^\top$.

Ba vector $v_1,v_2,v_3$ trực giao với nhau từng đôi một (tích vô hướng bằng 0), và đều có chuẩn 1 → **trực chuẩn**.


In [5]:
eigvalues, eigvectors = np.linalg.eigh(M)   # eigh trả về tăng dần
order = np.argsort(eigvalues)[::-1]         # sắp xếp giảm dần
eigvalues = eigvalues[order]
eigvectors = eigvectors[:, order]

print("Eigenvalues (giảm dần):", eigvalues)
print("Eigenvectors (theo cột):\n", eigvectors)

# so với kết quả tính tay
v1_hand = np.array([1,1,2])/np.sqrt(6)
v2_hand = np.array([1,-1,0])/np.sqrt(2)
v3_hand = np.array([1,1,-1])/np.sqrt(3)
print("\nKiểm tra trực giao (tích vô hướng đôi một):")
print(v1_hand @ v2_hand, v1_hand @ v3_hand, v2_hand @ v3_hand)

Eigenvalues (giảm dần): [6. 2. 0.]
Eigenvectors (theo cột):
 [[-0.4082 -0.7071 -0.5774]
 [-0.4082  0.7071 -0.5774]
 [-0.8165 -0.      0.5774]]

Kiểm tra trực giao (tích vô hướng đôi một):
0.0 0.0 0.0


## Bước 5–6. Singular values và right singular vectors

$$
\sigma_1=\sqrt{\lambda_1}=\sqrt6,\qquad
\sigma_2=\sqrt{\lambda_2}=\sqrt2,\qquad
\sigma_3=\sqrt{\lambda_3}=0
$$

$$
v_1=\frac{1}{\sqrt6}\begin{bmatrix}1\\1\\2\end{bmatrix},\qquad
v_2=\frac{1}{\sqrt2}\begin{bmatrix}1\\-1\\0\end{bmatrix},\qquad
v_3=\frac{1}{\sqrt3}\begin{bmatrix}1\\1\\-1\end{bmatrix}
$$


In [6]:
sigma = np.sqrt(np.clip(eigvalues, 0, None))
print("singular values:", sigma)

singular values: [2.4495 1.4142 0.    ]


## Bước 7. Tính $u_i = Av_i/\sigma_i$ với $\sigma_i>0$

**$u_1$:** $Av_1 = \dfrac{1}{\sqrt6}(c_1+c_2+2c_3) = \dfrac{1}{\sqrt6}(3,3,3,3)^\top$, do đó

$$
u_1=\frac{Av_1}{\sigma_1}=\frac{1}{\sqrt6\cdot\sqrt6}(3,3,3,3)^\top=\frac{1}{2}(1,1,1,1)^\top
$$

**$u_2$:** $Av_2=\dfrac{1}{\sqrt2}(c_1-c_2) = \dfrac{1}{\sqrt2}(1,-1,1,-1)^\top$, do đó

$$
u_2=\frac{Av_2}{\sigma_2}=\frac{1}{\sqrt2\cdot\sqrt2}(1,-1,1,-1)^\top=\frac{1}{2}(1,-1,1,-1)^\top
$$

Vì $\sigma_3=0$ nên **không thể** dùng công thức $u_3=Av_3/\sigma_3$ (chia cho 0). $u_3$ (và $u_4$) sẽ được bổ sung ở bước sau bằng cách chọn cơ sở trực chuẩn cho phần bù trực giao của $\operatorname{span}\{u_1,u_2\}$ trong $\mathbb{R}^4$.


In [7]:
u1 = (A @ v1_hand) / sigma[0]
u2 = (A @ v2_hand) / sigma[1]
print("u1 =", u1)
print("u2 =", u2)
print("||u1|| =", np.linalg.norm(u1), " ||u2|| =", np.linalg.norm(u2), " u1.u2 =", u1@u2)

u1 = [0.5 0.5 0.5 0.5]
u2 = [ 0.5 -0.5  0.5 -0.5]
||u1|| = 1.0000000000000002  ||u2|| = 0.9999999999999999  u1.u2 = 0.0


## Bước 8. Bổ sung vector để có Full SVD

Cần tìm $u_3,u_4\in\mathbb{R}^4$ trực chuẩn, trực giao với $u_1,u_2$, để $\{u_1,u_2,u_3,u_4\}$ là cơ sở trực chuẩn của $\mathbb{R}^4$.

Chọn:

$$
u_3=\frac{1}{\sqrt2}(1,0,-1,0)^\top,\qquad
u_4=\frac{1}{\sqrt2}(0,1,0,-1)^\top
$$

Kiểm tra nhanh: $u_3\cdot u_1=0,\ u_3\cdot u_2=0$; $u_4\cdot u_1=0,\ u_4\cdot u_2=0,\ u_4\cdot u_3=0$; $\|u_3\|=\|u_4\|=1$. Vậy đây là lựa chọn hợp lệ (không duy nhất, vì mọi cơ sở trực chuẩn khác của phần bù trực giao cũng đúng).

**Full SVD** $A=U\Sigma V^\top$ với:

$$
U=\begin{bmatrix}
\tfrac12 & \tfrac12 & \tfrac{1}{\sqrt2} & 0\\
\tfrac12 & -\tfrac12 & 0 & \tfrac{1}{\sqrt2}\\
\tfrac12 & \tfrac12 & -\tfrac{1}{\sqrt2} & 0\\
\tfrac12 & -\tfrac12 & 0 & -\tfrac{1}{\sqrt2}
\end{bmatrix}\in\mathbb{R}^{4\times4},
\qquad
\Sigma=\begin{bmatrix}\sqrt6&0&0\\0&\sqrt2&0\\0&0&0\\0&0&0\end{bmatrix}\in\mathbb{R}^{4\times3},
$$

$$
V^\top=\begin{bmatrix}
1/\sqrt6 & 1/\sqrt6 & 2/\sqrt6\\
1/\sqrt2 & -1/\sqrt2 & 0\\
1/\sqrt3 & 1/\sqrt3 & -1/\sqrt3
\end{bmatrix}\in\mathbb{R}^{3\times3}
$$


In [8]:
u3 = np.array([1,0,-1,0])/np.sqrt(2)
u4 = np.array([0,1,0,-1])/np.sqrt(2)

U = np.column_stack([u1, u2, u3, u4])
Sigma_full = np.zeros((4,3))
Sigma_full[0,0] = sigma[0]
Sigma_full[1,1] = sigma[1]
V = np.column_stack([v1_hand, v2_hand, v3_hand])

print("U =\n", U)
print("\nSigma (4x3) =\n", Sigma_full)
print("\nV^T =\n", V.T)

U =
 [[ 0.5     0.5     0.7071  0.    ]
 [ 0.5    -0.5     0.      0.7071]
 [ 0.5     0.5    -0.7071  0.    ]
 [ 0.5    -0.5     0.     -0.7071]]

Sigma (4x3) =
 [[2.4495 0.     0.    ]
 [0.     1.4142 0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.    ]]

V^T =
 [[ 0.4082  0.4082  0.8165]
 [ 0.7071 -0.7071  0.    ]
 [ 0.5774  0.5774 -0.5774]]


## Bước 9–10. Reduced SVD

Vì $\operatorname{rank}(A)=2$, chỉ cần giữ lại 2 singular values khác 0:

$$
A = U_r\,\Sigma_r\,V_r^\top
$$

$$
U_r=\begin{bmatrix}u_1 & u_2\end{bmatrix}=
\begin{bmatrix}
\tfrac12 & \tfrac12\\
\tfrac12 & -\tfrac12\\
\tfrac12 & \tfrac12\\
\tfrac12 & -\tfrac12
\end{bmatrix}\in\mathbb{R}^{4\times2},\qquad
\Sigma_r=\begin{bmatrix}\sqrt6 & 0\\0&\sqrt2\end{bmatrix}\in\mathbb{R}^{2\times2},\qquad
V_r^\top=\begin{bmatrix}v_1^\top\\v_2^\top\end{bmatrix}\in\mathbb{R}^{2\times3}
$$

**Kích thước:** $U_r\in\mathbb{R}^{4\times2}$, $\Sigma_r\in\mathbb{R}^{2\times2}$, $V_r^\top\in\mathbb{R}^{2\times3}$ (nói chung: $U_r\in\mathbb{R}^{m\times r}$, $\Sigma_r\in\mathbb{R}^{r\times r}$, $V_r^\top\in\mathbb{R}^{r\times n}$ với $r=\operatorname{rank}(A)$).


In [9]:
r = 2
U_r = U[:, :r]
Sigma_r = np.diag(sigma[:r])
V_r = V[:, :r]

print("U_r shape:", U_r.shape)
print("Sigma_r shape:", Sigma_r.shape)
print("V_r^T shape:", V_r.T.shape)
print("\nU_r =\n", U_r)
print("\nSigma_r =\n", Sigma_r)
print("\nV_r^T =\n", V_r.T)

U_r shape: (4, 2)
Sigma_r shape: (2, 2)
V_r^T shape: (2, 3)

U_r =
 [[ 0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  0.5]
 [ 0.5 -0.5]]

Sigma_r =
 [[2.4495 0.    ]
 [0.     1.4142]]

V_r^T =
 [[ 0.4082  0.4082  0.8165]
 [ 0.7071 -0.7071  0.    ]]


## Bước 11. Kiểm tra $U^\top U=I$, $V^\top V=I$, $U\Sigma V^\top=A$


In [10]:
print("U^T U =\n", np.round(U.T @ U, 10))
print("\nV^T V =\n", np.round(V.T @ V, 10))

A_reconstructed_full = U @ Sigma_full @ V.T
print("\nTái tạo A từ Full SVD:\n", A_reconstructed_full)
print("\nSai số so với A gốc:", np.max(np.abs(A_reconstructed_full - A)))

A_reconstructed_reduced = U_r @ Sigma_r @ V_r.T
print("\nTái tạo A từ Reduced SVD:\n", A_reconstructed_reduced)
print("\nSai số so với A gốc:", np.max(np.abs(A_reconstructed_reduced - A)))

# đối chiếu với SVD của numpy (dấu các vector có thể khác nhưng trị số singular values phải khớp)
U_np, s_np, Vt_np = np.linalg.svd(A)
print("\nSingular values từ numpy.linalg.svd:", s_np)
print("So với tính tay [sqrt6, sqrt2, 0]:", [np.sqrt(6), np.sqrt(2), 0])

U^T U =
 [[ 1. -0. -0. -0.]
 [-0.  1. -0.  0.]
 [-0. -0.  1.  0.]
 [-0.  0.  0.  1.]]

V^T V =
 [[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

Tái tạo A từ Full SVD:
 [[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]

Sai số so với A gốc: 2.220446049250313e-16

Tái tạo A từ Reduced SVD:
 [[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]

Sai số so với A gốc: 2.220446049250313e-16

Singular values từ numpy.linalg.svd: [2.4495 1.4142 0.    ]
So với tính tay [sqrt6, sqrt2, 0]: [np.float64(2.449489742783178), np.float64(1.4142135623730951), 0]


## Bước 12. Giải thích

**Vì sao có một singular value bằng 0?**
* Vì $\operatorname{rank}(A)=2<3=$ số cột của $A$. Số singular value khác 0 luôn đúng bằng $\operatorname{rank}(A)$, nên với $3$ giá trị $\sigma_1,\sigma_2,\sigma_3$ phải có đúng $3-2=1$ giá trị bằng 0.

**Singular vector ứng với singular value 0 liên hệ với null space của $A$ như thế nào?**
* $v_3$ (ứng với $\sigma_3=0$) chính là một cơ sở (trực chuẩn) của $\operatorname{null}(A)$: vì $Av_3=\sigma_3 u_3=0$ (thực ra không định nghĩa $u_3$ theo cách này, nhưng nói chung $A^\top A v_3=0\cdot v_3=0 \Rightarrow v_3^\top A^\top A v_3 = \|Av_3\|^2=0 \Rightarrow Av_3=0$). Điều này khớp với việc ta tìm được $\operatorname{null}(A)=\operatorname{span}\{(1,1,-1)\}$ ở Bước 1 (từ quan hệ $c_1+c_2=c_3$).

**Vì sao Reduced SVD vẫn tái tạo chính xác $A$?**
* Trong Full SVD, số hạng ứng với $\sigma_3=0$ đóng góp $\sigma_3 u_3 v_3^\top = 0$ vào tổng $A=\sum_i \sigma_i u_i v_i^\top$. Do đó bỏ đi thành phần này (và mọi thành phần $\sigma_i=0$ khác nếu có) không làm mất thông tin gì — Reduced SVD chỉ giữ lại đúng các thành phần có đóng góp thực sự (khác 0), nên vẫn tái tạo $A$ chính xác tuyệt đối, đồng thời tiết kiệm bộ nhớ/tính toán.


# Câu 2. Chọn $k$ cho Truncated SVD bằng tỷ lệ năng lượng

Ma trận dữ liệu $X$ có các singular values:

$$
\sigma_1=12,\quad\sigma_2=5,\quad\sigma_3=3,\quad\sigma_4=1
$$


In [11]:
sigmas = np.array([12, 5, 3, 1], dtype=float)

## Bước 1. Rank của $X$

Cả 4 singular values đều khác 0, nên:

$$
\operatorname{rank}(X)=4
$$


## Bước 2. Tổng năng lượng

$$
E_{\text{total}}=\sum_{i=1}^4\sigma_i^2 = 12^2+5^2+3^2+1^2 = 144+25+9+1 = 179
$$


In [12]:
energies = sigmas**2
E_total = energies.sum()
print("năng lượng từng thành phần:", energies)
print("E_total =", E_total)

năng lượng từng thành phần: [144.  25.   9.   1.]
E_total = 179.0


## Bước 3–4. Tính $R(k)$ và hoàn thành bảng

$$
R(k) = \frac{\sum_{i=1}^k \sigma_i^2}{E_{\text{total}}}
$$

- $k=1$: $\;144/179 \approx 0.8045$ (≈ 80.45%)
- $k=2$: $\;169/179 \approx 0.9441$ (≈ 94.41%)
- $k=3$: $\;178/179 \approx 0.9944$ (≈ 99.44%)
- $k=4$: $\;179/179 = 1.0000$ (100%)

| $k$ | Năng lượng giữ lại | Tỷ lệ $R(k)$ |
|---:|---:|---:|
| 1 | 144 | 80.45% |
| 2 | 169 | 94.41% |
| 3 | 178 | 99.44% |
| 4 | 179 | 100.00% |


In [13]:
cum_energy = np.cumsum(energies)
R = cum_energy / E_total
for k in range(1, 5):
    print(f"k={k}: năng lượng giữ lại = {cum_energy[k-1]:.0f}, R(k) = {R[k-1]*100:.2f}%")

k=1: năng lượng giữ lại = 144, R(k) = 80.45%
k=2: năng lượng giữ lại = 169, R(k) = 94.41%
k=3: năng lượng giữ lại = 178, R(k) = 99.44%
k=4: năng lượng giữ lại = 179, R(k) = 100.00%


## Bước 5. Tìm $k$ nhỏ nhất để giữ ít nhất 80% / 90% / 95% / 99% năng lượng

Từ bảng trên:

- **80%:** $R(1)=80.45\%\geq80\%$ → $k=1$
- **90%:** $R(1)=80.45\%<90\%$, $R(2)=94.41\%\geq90\%$ → $k=2$
- **95%:** $R(2)=94.41\%<95\%$, $R(3)=99.44\%\geq95\%$ → $k=3$
- **99%:** $R(2)=94.41\%<99\%$, $R(3)=99.44\%\geq99\%$ → $k=3$


In [14]:
thresholds = [0.80, 0.90, 0.95, 0.99]
for t in thresholds:
    k_min = np.argmax(R >= t) + 1   # chỉ số đầu tiên thỏa mãn
    print(f"Ngưỡng {int(t*100)}% -> k nhỏ nhất = {k_min} (R(k)={R[k_min-1]*100:.2f}%)")

Ngưỡng 80% -> k nhỏ nhất = 1 (R(k)=80.45%)
Ngưỡng 90% -> k nhỏ nhất = 2 (R(k)=94.41%)
Ngưỡng 95% -> k nhỏ nhất = 3 (R(k)=99.44%)
Ngưỡng 99% -> k nhỏ nhất = 3 (R(k)=99.44%)


## Bước 6–7. Tính $\|X-X_k\|_F=\sqrt{\sum_{i=k+1}^4\sigma_i^2}$ và hoàn thành bảng

- $k=1$: $\sqrt{25+9+1}=\sqrt{35}\approx 5.916$
- $k=2$: $\sqrt{9+1}=\sqrt{10}\approx 3.162$
- $k=3$: $\sqrt{1}=1.000$

| $k$ | $R(k)$ | $\|X-X_k\|_F$ |
|---:|---:|---:|
| 1 | 80.45% | 5.916 |
| 2 | 94.41% | 3.162 |
| 3 | 99.44% | 1.000 |


In [15]:
for k in range(1, 4):
    residual_energy = energies[k:].sum()   # sigma_{k+1}^2 + ... + sigma_4^2
    frob_norm = np.sqrt(residual_energy)
    print(f"k={k}: R(k)={R[k-1]*100:.2f}%,  ||X-X_k||_F = {frob_norm:.3f}")

k=1: R(k)=80.45%,  ||X-X_k||_F = 5.916
k=2: R(k)=94.41%,  ||X-X_k||_F = 3.162
k=3: R(k)=99.44%,  ||X-X_k||_F = 1.000


## Bước 8. Chọn $k$ khi $\sigma_4$ chủ yếu là nhiễu

Nếu $\sigma_4=1$ chủ yếu biểu diễn nhiễu, ta nên **chọn $k=3$**: giữ lại các thành phần $\sigma_1,\sigma_2,\sigma_3$ (đã chiếm tới **99.44%** năng lượng của dữ liệu), và loại bỏ $\sigma_4$ — thành phần vừa đóng góp năng lượng không đáng kể (chỉ 0.56%), vừa được giả định là nhiễu. Việc loại bỏ này giúp mô hình/xấp xỉ $X_3$ vừa gần như không mất thông tin thật, vừa "khử nhiễu" cho dữ liệu.

## Bước 9. Trả lời các câu hỏi lý thuyết

**Vì sao singular values phải được sắp xếp giảm dần?**
* Theo định nghĩa/qui ước của SVD, $\sigma_1\geq\sigma_2\geq\dots\geq0$. Nhờ vậy, tổng $X=\sum_i\sigma_i u_iv_i^\top$ liệt kê các "hướng" đóng góp năng lượng từ lớn đến nhỏ, và định lý Eckart–Young đảm bảo rằng lấy $k$ số hạng **đầu tiên** (ứng với $k$ singular values lớn nhất) luôn cho xấp xỉ hạng-$k$ **tốt nhất có thể** (theo chuẩn Frobenius hoặc chuẩn phổ) trong số mọi ma trận hạng $k$. Nếu không sắp xếp giảm dần, việc "cắt" $k$ số hạng đầu sẽ không còn ý nghĩa tối ưu này.

**Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?**
* Không. Giữ nhiều hơn giúp giảm sai số xấp xỉ $\|X-X_k\|_F$, nhưng đồng thời:
    * Tốn nhiều bộ nhớ và chi phí tính toán hơn (vì $X_k$ cần lưu $k$ cặp vector $u_i,v_i$ và $k$ giá trị $\sigma_i$);
    * Các singular values nhỏ nhất thường tương ứng với nhiễu hoặc các biến động không đáng kể trong dữ liệu — giữ lại chúng có thể làm mô hình "khớp" luôn cả nhiễu (overfitting), làm giảm khả năng tổng quát hoá.

**Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu?**
- $k$ nhỏ → nén mạnh (ít tham số lưu trữ, tính toán nhanh) nhưng $R(k)$ thấp → mất nhiều thông tin, sai số xấp xỉ $\|X-X_k\|_F$ lớn.
- $k$ lớn → giữ được nhiều năng lượng/thông tin hơn ($R(k)$ cao, sai số nhỏ) nhưng mức độ nén thấp (gần với dữ liệu gốc, tốn nhiều tham số).

Việc chọn $k$ trong thực tế luôn là bài toán đánh đổi: chọn $k$ nhỏ nhất sao cho $R(k)$ đạt một ngưỡng chấp nhận được (ví dụ 95%, 99%), để vừa nén dữ liệu hiệu quả vừa giữ được phần lớn thông tin hữu ích, đồng thời có xu hướng loại bỏ các thành phần nhiễu ứng với các singular values nhỏ nhất.
